# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'Free Trial (415f196b-dbde-48a5-8a04-3897ea12069e)'
      subscriptionId: '415f196b-dbde-48a5-8a04-3897ea12069e'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'amedina-storage-rg'
      location: 'West Europe'
      templateLocation: 'Linked artifact'
      csmFile: '$(System.DefaultWorkingDirectory)/**/storage-template.json'
      csmParametersFile: '$(System.DefaultWorkingDirectory)/**/storage-parameters.json'
      deploymentMode: 'Incremental'
