trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Application
  batch: True
name: $(date:yyyyMMdd)$(rev:.r)

pool:
  name: Azure Pipelines
steps:
- task: ArchiveFiles@1
  displayName: 'Archive files'
  inputs:
    rootFolder: '$(System.DefaultWorkingDirectory)/Application'
    includeRootFolder: false
    archiveType: zip

- task: CopyFiles@2
  displayName: 'Copy ARM templates'
  inputs:
    SourceFolder: ArmTemplates
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

