# File: main-pipeline.yml
# This is the top-level YAML file that will orchestrate the pipeline
trigger:
  branches:
    include:
    - refs/heads/master
  paths:
    include:
    - Application/index.php

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: build-pipeline.yml
- template: release-staging-pipeline.yml
- template: manual-validation.yml
- template: release-prod-pipeline.yml


