trigger:
- none

stages:
- stage: Validate

  jobs:
  - job: waitForValidation
    displayName: Wait for external validation  
    pool: server    
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:   
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
          notifyUsers: |
                attila.media@gmail.com
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'resume'