resources:
  pipelines:
  - pipeline: manual-validation 
    source: release-staging 
    project: inlinemarket-excercise 
    trigger: true 

jobs:
- job: waitForValidation
  displayName: Wait for external validation  
  pool: Azure pipelines    
  timeoutInMinutes: 4320 # job times out in 3 days
  steps:   

  - task: ManualIntervention@8
    inputs:
      instructions: 'Please approve'
      emailRecipients: 'attila.medina@gmail.com'