resources:
  pipelines:
  - pipeline: release-prod 
    source: manual-validation 
    project: inlinemarket-excercise 
    trigger: true 

jobs:
- job: releaseProd
  displayName: Release prod
  pool: Azure pipelines    

  steps:
  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy Azure App Service'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Free Trial(7)(415f196b-dbde-48a5-8a04-3897ea12069e)'
      appType: 'webAppLinux'
      WebAppName: 'inlinemarket-assesment'
      deployToSlotOrASE: true
      ResourceGroupName: 'inlinemarket-assesment-rg'
      SlotName: 'production'
      packageForLinux: '$(Build.ArtifactStagingDirectory)'
      RuntimeStack: 'PHP|8.1'
      ScriptType: 'Inline Script'
      InlineScript: |
        if [ -f  composer.json ] 
        then 
          echo "Found composer.json" 
          composer install 
        else 
          echo "Composer.json not found. Skipping composer install" 
        fi

