resources:
  pipelines:
  - pipeline: release-staging 
    source: build-pipeline 
    project: inlinemarket-excercise 
    trigger: true 

jobs:
- job: Deploy
  displayName: Release staging
  steps:
  - task: AzureResourceGroupDeployment@2
    displayName: 'Azure Deployment:Create Azure App Service'
    inputs:
      azureSubscription: 'inlinemarket-excercise - Azure'
      resourceGroupName: 'inlinemarket-excercise-rg'
      location: 'West Europe'
      csmFile: '$(System.DefaultWorkingDirectory)/**/container-webapp-template.json'
      overrideParameters: '-webAppName inlinemarket-excercise -hostingPlanName inlinemarket-excercise-plan -appInsightsLocation "West Europe" -sku "S1 Standard" -registryName "inlinemarketexcerciseacr" -registryLocation "South Central US" -registrySku "Standard" -imageName inlinemarketexcercise:$(Build.BuildId)'
# Deploy staging slot
  - task: AzureResourceGroupDeployment@2
    displayName: 'Azure Deployment:Create Test slot'
    inputs:
      azureSubscription: 'inlinemarket-excercise - Azure'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'inlinemarket-excercise-rg'
      location: 'West Europe'
      templateLocation: 'Linked artifact'
      csmFile: '$(System.DefaultWorkingDirectory)/**/slot-template.json'
      deploymentMode: 'Incremental'
  - task: AzureRmWebAppDeployment@3
    displayName: 'Deploy Azure App Service'
    inputs:
      azureSubscription: 'inlinemarket-excercise - Azure'
      appType: applinux
      WebAppName: 'inlinemarket-excercise'
      DeployToSlotFlag: true
      ResourceGroupName: 'inlinemarket-excercise-rg'
      SlotName: 'staging'
      DockerNamespace: inlinemarketexcerciseacr.azurecr.io
      DockerRepository: inlinemarketexcercise
      DockerImageTag: '$(Build.BuildId)'
      TakeAppOfflineFlag: true
      UseWebDeploy: true
      RenameFilesFlag: true