resources:
  pipelines:
  - pipeline: release-staging # Name of the pipeline resource.
    source: build-pipeline # The name of the pipeline referenced by this pipeline resource.
    project: inlinemarket-excercise # Required only if the source pipeline is in another project
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes


stages:
- stage: Deploy

  jobs:
  - job: Deploy
    displayName: Release staging
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Azure App Service'
      inputs:
        azureSubscription: 'inlinemarket-excercise - Azure'
        resourceGroupName: 'inlinemarket-excercise-rg'
        location: 'West Europe'
        csmFile: '$(System.DefaultWorkingDirectory)/**/container-webapp-template.json'
        overrideParameters: '-webAppName inlinemarket-excercise -hostingPlanName inlinemarket-excercise-plan -appInsightsLocation "West Europe" -sku "S1 Standard" -registryName "inlinemarketexcerciseacr" -registryLocation "South Central US" -registrySku "Standard" -imageName inlinemarketexcercise:$(Build.BuildId)'

    - task: AzureRmWebAppDeployment@3
      displayName: 'Deploy Azure App Service'
      inputs:
        azureSubscription: 'inlinemarket-excercise - Azure'
        appType: applinux
        WebAppName: 'inlinemarket-excercise'
        deployToSlotOrASE: true
        ResourceGroupName: 'inlinemarket-excercise-rg'
        SlotName: 'staging'
        DockerNamespace: inlinemarketexcerciseacr.azurecr.io
        DockerRepository: inlinemarketexcercise
        DockerImageTag: '$(Build.BuildId)'
        TakeAppOfflineFlag: true
        UseWebDeploy: true
        RenameFilesFlag: true